### ISSUE TITLE
Please add a LICENSE to this repository.

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/canary-harvester#1]
Hi! This public repo has unlicensed content in it, which prevents it from being used by non-Mozilla staff. Please consider either adding a LICENSE (our default here would be MPL2) or making the repository private so that it's only visible to staff.

MPL2 plain-text edition: https://www.mozilla.org/media/MPL/2.0/index.815ca599c9df.txt

**Comment by franziskuskiefer** [comment]
There's an MPL2 LICENSE file in the repo since creation

**Comment by floatingatoll** [comment]
You're right! I'm so sorry. This was meant for a different repository. :( Someone is working on a bot that might make this more automated in the future and that should help prevent human mistakes like mine.
